version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - USE_FAKE_STORAGE=true
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G 
   